In [88]:
import pandas as pd
import numpy as np

In [89]:
def load_data_from_github(url: str) -> pd.DataFrame:
    df = pd.read_csv(url)
    return df

In [90]:
def get_max_close(symbol):
    return symbol['Close'].max()

In [91]:
if __name__ == '__main__':
    AMD = load_data_from_github(
        'https://raw.githubusercontent.com/huseinzol05/Stock-Prediction-Models/refs/heads/master/dataset/AMD.csv'
    )
    GOOG = load_data_from_github(
        'https://raw.githubusercontent.com/huseinzol05/Stock-Prediction-Models/refs/heads/master/dataset/AMD.csv'
    )

    print(f'Max Close AAPL: {AMD["Close"].max()}')
    print(f'Max Close IBM: {GOOG["Close"].max()}')


Max Close AAPL: 32.720001
Max Close IBM: 32.720001


In [97]:

start_date = '2018-05-23'
end_date = '2019-05-23'

dates = pd.date_range(start=start_date, end=end_date)


In [105]:
TWTR = load_data_from_github(
    'https://raw.githubusercontent.com/huseinzol05/Stock-Prediction-Models/refs/heads/master/dataset/TWTR.csv'
)

Date       Open       High        Low      Close  Adj Close  \
0    2018-05-23  32.700001  33.430000  32.599998  33.419998  33.419998   
1    2018-05-24  33.439999  33.759998  33.119999  33.520000  33.520000   
2    2018-05-25  33.540001  33.990002  33.310001  33.630001  33.630001   
3    2018-05-29  33.419998  34.830002  33.349998  34.040001  34.040001   
4    2018-05-30  34.200001  34.660000  34.080002  34.360001  34.360001   
..          ...        ...        ...        ...        ...        ...   
247  2019-05-17  37.830002  38.130001  37.470001  37.500000  37.500000   
248  2019-05-20  37.119999  37.730000  36.919998  37.150002  37.150002   
249  2019-05-21  37.470001  37.860001  37.330002  37.470001  37.470001   
250  2019-05-22  37.410000  39.320000  37.240002  38.580002  38.580002   
251  2019-05-23  38.150002  38.290001  36.799999  37.189999  37.189999   

       Volume  
0    13407500  
1    14491900  
2    10424400  
3    22086700  
4    14588200  
..        ...  
247   9090300  
248   9411900  
249   8861400  
250  21093500  
251  18096372  

[252 rows x 7 columns]

In [149]:
base = TWTR[['Date', 'TWTR']].copy()
base = base.loc[:, ~base.columns.duplicated()].copy()
base = base.join(AMD[['AMD']],how='left')
base = base.join(GOOG[['GOOG']],how='left')

In [155]:
base[['TWTR','AMD']]

TWTR        AMD
0    33.419998  13.100000
1    33.520000  13.410000
2    33.630001  13.540000
3    34.040001  13.360000
4    34.360001  13.820000
..         ...        ...
247  37.500000  27.500000
248  37.150002  26.680000
249  37.470001  27.350000
250  38.580002  27.410000
251  37.189999  26.309999

[252 rows x 2 columns]

In [165]:
import matplotlib.pyplot as plt

def plot(df,title='Close Price History'):
    plt.plot(df)
    plt.title(title)
    plt.xlabel('Date')
    plt.ylabel('Close')
    plt.show()

In [167]:
plot(df= base['AMD'],title='AMD')
plot(df= base['GOOG'],title='GOOG')

In [178]:
import numpy as np

def test_run():
    print(np.array([(2,3,4,5),(5,4,3,2)]))
    print(np.empty((2,3)))
    print(np.ones((2,3)))
    print(np.random.random((2,3)))
    print(np.random.normal(50,10,size=(2,3)))
    print(np.random.randint(10))
    a = np.random.random((2,3))
    print(a.shape)
    print(a.size)

if __name__ == '__main__':
    test_run()

[[2 3 4 5]
 [5 4 3 2]]
[[0.07323804 0.43708078 0.35561225]
 [0.61474714 0.55547599 0.51023037]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.82104016 0.97493065 0.65173095]
 [0.5001175  0.65155473 0.27564326]]
[[46.47931892 47.87942409 38.27765398]
 [51.49579643 64.19189864 49.94582049]]
5
(2, 3)
6
